/*
 * Nsmf_EventExposure
 *
 * Session Management Event Exposure Service API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

// Task2: Nsmf_EventExposure subscription handlers (TS 29.508).
// Behavior summary: Create returns 201 + Location; Delete returns 204; errors return ProblemDetails.
package sbi

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gin-gonic/gin"
	"github.com/google/uuid"

	"github.com/free5gc/openapi"
	"github.com/free5gc/openapi/models"
	smf_context "github.com/free5gc/smf/internal/context"
	"github.com/free5gc/smf/internal/logger"
	"github.com/free5gc/util/metrics/sbi"
)

type nsmfEventExposureRequest struct {
	Supi      string                          `json:"supi"`
	NotifId   string                          `json:"notifId"`
	NotifUri  string                          `json:"notifUri"`
	EventSubs []nsmfEventExposureEventSubItem `json:"eventSubs"`
}

type nsmfEventExposureEventSubItem struct {
	Event     string                     `json:"event"`
	UpfEvents []nsmfEventExposureUpfEvent `json:"upfEvents"`
}

type nsmfEventExposureUpfEvent struct {
	Type                     string   `json:"type"`
	MeasurementTypes         []string `json:"measurementTypes"`
	GranularityOfMeasurement string   `json:"granularityOfMeasurement,omitempty"`
}

func (s *Server) getEventExposureRoutes() []Route {
	return []Route{
		{
			Name:    "Index",
			Method:  http.MethodGet,
			Pattern: "/",
			APIFunc: func(c *gin.Context) {
				c.JSON(http.StatusOK, gin.H{"status": "Service Available"})
			},
		},
		{
			Name:    "CreateIndividualSubcription",
			Method:  http.MethodPost,
			Pattern: "/subscriptions",
			APIFunc: s.HTTPCreateIndividualSubcription,
		},
		{
			Name:    "DeleteIndividualSubcription",
			Method:  http.MethodDelete,
			Pattern: "/subscriptions/:subId",
			APIFunc: s.HTTPDeleteIndividualSubcription,
		},
		{
			Name:    "GetIndividualSubcription",
			Method:  http.MethodGet,
			Pattern: "/subscriptions/:subId",
			APIFunc: s.HTTPGetIndividualSubcription,
		},
		{
			Name:    "ReplaceIndividualSubcription",
			Method:  http.MethodPut,
			Pattern: "/subscriptions/:subId",
			APIFunc: s.HTTPReplaceIndividualSubcription,
		},
	}
}

// SubscriptionsPost -
func (s *Server) HTTPCreateIndividualSubcription(c *gin.Context) {
	logger.SBILog.Info("Receive Create Event Exposure Subscription Request")

	var req nsmfEventExposureRequest
	if err := c.ShouldBindJSON(&req); err != nil {
		problemDetail := "[Request Body] " + err.Error()
		logger.SBILog.Errorln(problemDetail)
		problemDetails := openapi.ProblemDetailsMalformedReqSyntax(problemDetail)
		c.Set(sbi.IN_PB_DETAILS_CTX_STR, http.StatusText(int(problemDetails.Status)))
		c.JSON(int(problemDetails.Status), problemDetails)
		return
	}

	if problemDetails := validateNsmfEventExposureRequest(&req); problemDetails != nil {
		c.Set(sbi.IN_PB_DETAILS_CTX_STR, http.StatusText(int(problemDetails.Status)))
		c.JSON(int(problemDetails.Status), problemDetails)
		return
	}

	subId := uuid.New().String()
	eventSubsState := make([]smf_context.NsmfEventExposureEventSubState, 0, len(req.EventSubs))
	for _, sub := range req.EventSubs {
		upfEventsState := make([]smf_context.NsmfEventExposureUpfEventState, 0, len(sub.UpfEvents))
		for _, upfEvent := range sub.UpfEvents {
			upfEventsState = append(upfEventsState, smf_context.NsmfEventExposureUpfEventState{
				Type:                     upfEvent.Type,
				MeasurementTypes:         append([]string(nil), upfEvent.MeasurementTypes...),
				GranularityOfMeasurement: upfEvent.GranularityOfMeasurement,
			})
		}
		eventSubsState = append(eventSubsState, smf_context.NsmfEventExposureEventSubState{
			Event:     sub.Event,
			UpfEvents: upfEventsState,
		})
	}

	state := &smf_context.NsmfEventExposureSubState{
		NsmfSubId: subId,
		Supi:      req.Supi,
		NotifId:   req.NotifId,
		NotifUri:  req.NotifUri,
		EventSubs: eventSubsState,
	}
	smf_context.GetSelf().NsmfEventExposureSubs.Put(state)

	location := subId
	if c.Request != nil {
		protocol := "http"
		if c.Request.TLS != nil {
			protocol += "s"
		}
		basePath := strings.TrimSuffix(c.Request.URL.Path, "/")
		location = fmt.Sprintf("%s://%s%s/%s", protocol, c.Request.Host, basePath, subId)
	}

	response := models.NsmfEventExposure{
		SubId:    subId,
		Supi:     req.Supi,
		NotifId:  req.NotifId,
		NotifUri: req.NotifUri,
	}
	if len(req.EventSubs) != 0 {
		response.EventSubs = make([]models.SmfEventExposureEventSubscription, 0, len(req.EventSubs))
		for _, sub := range req.EventSubs {
			response.EventSubs = append(response.EventSubs, models.SmfEventExposureEventSubscription{
				Event: models.SmfEvent(sub.Event),
			})
		}
	}

	logger.SBILog.WithFields(map[string]interface{}{
		logger.FieldSupi: req.Supi,
		"notif_id":       req.NotifId,
		"nsmf_sub_id":    subId,
		"http_status":    http.StatusCreated,
	}).Info("Nsmf_EventExposure subscription created")

	c.Header("Location", location)
	c.JSON(http.StatusCreated, response)
}

// SubscriptionsSubIdDelete -
func (s *Server) HTTPDeleteIndividualSubcription(c *gin.Context) {
	subId := strings.TrimSpace(c.Param("subId"))
	if subId == "" {
		problemDetails := openapi.ProblemDetailsMalformedReqSyntax("subId is required")
		c.Set(sbi.IN_PB_DETAILS_CTX_STR, http.StatusText(int(problemDetails.Status)))
		c.JSON(int(problemDetails.Status), problemDetails)
		return
	}

	state, ok := smf_context.GetSelf().NsmfEventExposureSubs.Delete(subId)
	if !ok {
		logger.SBILog.WithFields(map[string]interface{}{
			"nsmf_sub_id": subId,
			"http_status": http.StatusNotFound,
		}).Info("Nsmf_EventExposure subscription not found")

		problemDetails := openapi.ProblemDetailsDataNotFound("subscription not found")
		c.Set(sbi.IN_PB_DETAILS_CTX_STR, http.StatusText(int(problemDetails.Status)))
		c.JSON(int(problemDetails.Status), problemDetails)
		return
	}

	logger.SBILog.WithFields(map[string]interface{}{
		logger.FieldSupi: state.Supi,
		"notif_id":       state.NotifId,
		"nsmf_sub_id":    subId,
		"http_status":    http.StatusNoContent,
	}).Info("Nsmf_EventExposure subscription deleted")

	c.Status(http.StatusNoContent)
}

// SubscriptionsSubIdGet -
func (s *Server) HTTPGetIndividualSubcription(c *gin.Context) {
	c.JSON(http.StatusNotImplemented, gin.H{})
}

// SubscriptionsSubIdPut -
func (s *Server) HTTPReplaceIndividualSubcription(c *gin.Context) {
	c.JSON(http.StatusNotImplemented, gin.H{})
}

func validateNsmfEventExposureRequest(req *nsmfEventExposureRequest) *models.ProblemDetails {
	if req == nil {
		return openapi.ProblemDetailsMalformedReqSyntax("empty request")
	}
	if strings.TrimSpace(req.Supi) == "" {
		return openapi.ProblemDetailsMalformedReqSyntax("supi is required")
	}
	if len(req.EventSubs) == 0 {
		return openapi.ProblemDetailsMalformedReqSyntax("eventSubs is required")
	}

	allowedMeasurements := map[string]struct{}{
		"VOLUME_MEASUREMENT":     {},
		"THROUGHPUT_MEASUREMENT": {},
	}

	hasUpfEvent := false
	hasUserDataUsage := false

	for _, sub := range req.EventSubs {
		if strings.TrimSpace(sub.Event) != "UPF_EVENT" {
			continue
		}
		hasUpfEvent = true
		for _, upfEvent := range sub.UpfEvents {
			if strings.TrimSpace(upfEvent.Type) != "USER_DATA_USAGE_MEASURES" {
				continue
			}
			if len(upfEvent.MeasurementTypes) == 0 {
				return openapi.ProblemDetailsMalformedReqSyntax("measurementTypes must not be empty")
			}
			for _, measurement := range upfEvent.MeasurementTypes {
				if _, ok := allowedMeasurements[measurement]; !ok {
					return openapi.ProblemDetailsMalformedReqSyntax(
						fmt.Sprintf("unsupported measurementTypes value: %s", measurement),
					)
				}
			}
			hasUserDataUsage = true
		}
	}

	if !hasUpfEvent {
		return openapi.ProblemDetailsMalformedReqSyntax("eventSubs must include UPF_EVENT")
	}
	if !hasUserDataUsage {
		return openapi.ProblemDetailsMalformedReqSyntax(
			"upfEvents must include USER_DATA_USAGE_MEASURES with measurementTypes",
		)
	}

	return nil
}
